# Generated by Django 6.0.4 on 2026-05-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productview',
            name='orders_prod_product_0ab591_idx',
        ),
        migrations.DeleteModel(
            name='ProductView',
        ),
    ]
