# Generated by Django 6.0.4 on 2026-05-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
