# Generated by Django 6.0.4 on 2026-05-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collection_lookbook_tag_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='collections/'),
        ),
    ]
