# Generated by Django 6.0.4 on 2026-05-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_collection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookbook',
            name='cover_image',
            field=models.ImageField(default='placeholder.jpg', upload_to='lookbooks/covers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='products/'),
        ),
    ]
