# Generated by Django 6.0.4 on 2026-05-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lookbook_cover_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(upload_to='collections/'),
        ),
        migrations.AlterField(
            model_name='lookbook',
            name='cover_image',
            field=models.ImageField(upload_to='lookbooks/covers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
